#!/bin/bash

if [ -f /usr/share/applications/kde-mimeapps.list ]; then
    sed -i "/pkg-installer-demo/d" /usr/share/applications/kde-mimeapps.list
else
    sed -i "/pkg-installer-demo/d" /usr/share/applications/mimeapps.list
fi